### ISSUE TITLE
getStartFrame, getEndFrame for SubRecordingExtractor

### ISSUE THREAD

**Issue by colehurwitz31** [colehurwitz31/spikeinterface#27]
I think it would be valuable for the SubRecordingExtractor to have this functionality.

**Comment by colehurwitz31** [comment]
I think it makes sense for the SubRecordingExtractor to return all the details that were put in the initialization like epoch_name and channel_ids since I may want to check what I set earlier. I don't think it would be that confusing

**Comment by magland** [comment]
I think I disagree. It's like if you crop an image and store it as a new .jpg... you don't need to store with that cropped image where it came from. That would get too confusing, because you may crop an image that was already cropped from a different image. It's better to keep track of that information elsewhere. (See my comment on the other issue).
